package com.example.ridesafev2.data.database


import android.os.Parcelable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.android.gms.maps.model.LatLng
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "location_table") // User Entity represents a table within the database.
data class Location(
    @PrimaryKey(autoGenerate = true) val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    @ColumnInfo(name = "location") val current_location: Int,
    @ColumnInfo(name = "destination") val destination: Int,
    //val adventureTime:
):Parcelable